/**
 * Registered human voiceover assets for animal words.
 */
export const ANIMAL_AUDIO_REGISTRY: Record<string, any> = {
  cat: require('../assets/sounds/animals/cat.wav'),
  dog: require('../assets/sounds/animals/dog.wav'),
  cow: require('../assets/sounds/animals/cow.wav'),
  horse: require('../assets/sounds/animals/horse.wav'),
  rabbit: require('../assets/sounds/animals/rabbit.wav'),
  lion: require('../assets/sounds/animals/lion.wav'),
  elephant: require('../assets/sounds/animals/elephant.wav'),
  bear: require('../assets/sounds/animals/bear.wav'),
  monkey: require('../assets/sounds/animals/monkey.wav'),
  giraffe: require('../assets/sounds/animals/giraffe.wav'),
  bird: require('../assets/sounds/animals/bird.wav'),
  chicken: require('../assets/sounds/animals/chicken.wav'),
  duck: require('../assets/sounds/animals/duck.wav'),
  owl: require('../assets/sounds/animals/owl.wav'),
  eagle: require('../assets/sounds/animals/eagle.wav'),
  fish: require('../assets/sounds/animals/fish.wav'),
  dolphin: require('../assets/sounds/animals/dolphin.wav'),
  whale: require('../assets/sounds/animals/whale.wav'),
  swan: require('../assets/sounds/animals/swan.wav'),
  koala: require('../assets/sounds/animals/koala.wav'),
  tiger: require('../assets/sounds/animals/tiger.wav'),
  panda: require('../assets/sounds/animals/panda.wav'),
  wolf: require('../assets/sounds/animals/wolf.wav'),
  fox: require('../assets/sounds/animals/fox.wav'),
  pig: require('../assets/sounds/animals/pig.wav'),
  bee: require('../assets/sounds/animals/bee.wav'),
  ant: require('../assets/sounds/animals/ant.wav'),
  worm: require('../assets/sounds/animals/worm.wav'),
  mouse: require('../assets/sounds/animals/mouse.wav'),
  hamster: require('../assets/sounds/animals/hamster.wav'),
  deer: require('../assets/sounds/animals/deer.wav'),
  goat: require('../assets/sounds/animals/goat.wav'),
  sheep: require('../assets/sounds/animals/sheep.wav'),
  camel: require('../assets/sounds/animals/camel.wav'),
  donkey: require('../assets/sounds/animals/donkey.wav'),
  zebra: require('../assets/sounds/animals/zebra.wav'),
  snake: require('../assets/sounds/animals/snake.wav'),
  frog: require('../assets/sounds/animals/frog.wav'),
  seal: require('../assets/sounds/animals/seal.wav'),
  goose: require('../assets/sounds/animals/goose.wav'),
  crab: require('../assets/sounds/animals/crab.wav'),
  // --- Colors ---
  red: require('../assets/sounds/colors/red.wav'),
  blue: require('../assets/sounds/colors/blue.wav'),
  green: require('../assets/sounds/colors/green.wav'),
  yellow: require('../assets/sounds/colors/yellow.wav'),
  orange: require('../assets/sounds/colors/orange.wav'),
  purple: require('../assets/sounds/colors/purple.wav'),
  pink: require('../assets/sounds/colors/pink.wav'),
  black: require('../assets/sounds/colors/black.wav'),
  white: require('../assets/sounds/colors/white.wav'),
};

export const CUSTOM_AUDIO_REGISTRY = ANIMAL_AUDIO_REGISTRY;

